on: [push]

jobs:
  scorecard:
    runs-on: ubuntu-latest
    name: Run the scorecard
    steps:
      - name: scorecard_name
        id: scorecard_step
        uses: sammachin/hello-world-docker-action@v1.4
        with:
          package: 'node-red-contrib-ngrok'
      # Use the output from the `hello` step
      - name: output_name
        run: echo "${{ steps.scorecard_name.outputs.scorecard }}"
